export { default as  Header } from './header/Header'
export { default as  About } from './about/About'
export { default as  Skills } from './skills/Skills'
export { default as  Projects } from './projects/Projects'
export { default as  LanguageSwitch } from './language-switch/LanguageSwitch'
export { default as  ScrollToTop } from './scroll-to-top/ScrollToTop'
